name: rectifier-monitoring
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310h540bb41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - greenlet=3.2.4=py310h885b0b7_0
  - intel-openmp=2025.0.0=haa95532_1164
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py310h0b37514_0
  - mkl_fft=2.1.1=py310h300f80d_0
  - mkl_random=1.3.0=py310ha5e6156_0
  - numexpr=2.14.1=py310h7660c64_0
  - numpy=2.2.5=py310h7894be3_2
  - numpy-base=2.2.5=py310h7794460_2
  - openssl=3.0.18=h543e019_0
  - pandas=2.3.3=py310h42c1672_1
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py310haa95532_0
  - pyyaml=6.0.3=py310hb9a58be_0
  - setuptools=80.9.0=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - sqlalchemy=2.0.43=py310hda9a48d_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - typing-extensions=4.15.0=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - blinker==1.9.0
      - click==8.3.1
      - colorama==0.4.6
      - flask==3.1.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - pymodbus==3.11.4
      - werkzeug==3.1.4
prefix: C:\Users\anshu\anaconda3\envs\rectifier-monitoring
